---
galaxy_info:
  author: mrhis
  description: Common node role for MRHIS (OS, users, firewall, selinux, ssh,
    sudo, communication, downloads, tests, report)
  license: MIT
  min_ansible_version: 2.9
dependencies: []
