#!/usr/bin/env bash
set -euo pipefail

ANSIBLE_ENV_DIR="$HOME/.ansible/conf"
ANSIBLE_ENV_FILE="$ANSIBLE_ENV_DIR/env.yml"
VAULT_PASS_FILE="$ANSIBLE_ENV_DIR/.vaultpass.text"
if [ ! -s "$VAULT_PASS_FILE" ]; then
  VAULT_PASS_FILE="$ANSIBLE_ENV_DIR/.vaultpass.txt"
fi
if [ ! -s "$VAULT_PASS_FILE" ]; then
  echo "No vault password file found in $ANSIBLE_ENV_DIR" >&2
  exit 2
fi
if [ ! -f "$ANSIBLE_ENV_FILE" ]; then
  echo "No env.yml found at $ANSIBLE_ENV_FILE" >&2
  exit 3
fi

TIMESTAMP=$(date +%s)
TMP_PLAIN=$(mktemp /tmp/env_plain.XXXXXX)
TMP_CLEAN=$(mktemp /tmp/env_clean.XXXXXX)
BACKUP="${ANSIBLE_ENV_FILE}.bak.${TIMESTAMP}"
cp "$ANSIBLE_ENV_FILE" "$BACKUP" || true

ansible-vault view --vault-password-file "$VAULT_PASS_FILE" "$ANSIBLE_ENV_FILE" > "$TMP_PLAIN"

awk 'BEGIN{skip=0}
  /^OPENSHIFT_PULL_SECRET[[:space:]]*:/ { skip=1; next }
  { if (skip && $0 ~ /^[^[:space:]]/) { skip=0 } }
  { if (!skip) print }' "$TMP_PLAIN" > "$TMP_CLEAN"

cat >> "$TMP_CLEAN" <<'YAML'

OPENSHIFT_PULL_SECRET: |
  {"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZGI1MGFkZmQ3Yjg2NDk4ZDg1NTY1NTQzMTI0ZjU4ZWY6MjFJU0FDSU1QUDlZTFlKSFhFMjQwN0hCOUk3UU1NNTBUT0ZVWVk2NFY5UzZRV1FWRTlXNEVHVDZHM1ZCQ1VTMQ==","email":"shadd@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZGI1MGFkZmQ3Yjg2NDk4ZDg1NTY1NTQzMTI0ZjU4ZWY6MjFJU0FDSU1QUDlZTFlKSFhFMjQwN0hCOUk3UU1NNTBUT0ZVWVk2NFY5UzZRV1FWRTlXNEVHVDZHM1ZCQ1VTMQ==","email":"shadd@redhat.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWZlNWQ2ZmI5LWFhZWYtNDRiMi1hZGM0LTIwMzI5ODFmMDJiNDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtNV05qWmpWbU5EaG1aamswTVRZM09URXdNV0V5TmpreE9USmxaVFJrWXlKOS5mVm5xZlRtWWMxUFBibTBsSVpIbGdqckxyMGNGRTNKOUlROWxOU1otYWtPYlI4eEtFVkIxdl84TkE1SzRhU3ZoNzJRNV9hQlhEUmI3dzZrUldGNnhBeGR6Q0pvdmFsYmwtU2lKWTd0M29nUnBxc1o4WF82WmdGSmpfbmVTc2RFandqYm50RzVMbnhpNmRJcnJDOV8tVlVmLU1fd3hScDRNa2RMUXV5SmN2NzZPTXZsYWM1M0FzZ01aeW1lazEtY2c3X0pic1QydXZTanhQbGxoOEZpSVMzS1BMdk1PalZLWW14NTNDR19Md01rVmg3cHdfSFdFbEVDVnF1WjBlS3k2bFBuWkZhb2VJUjFyTmlkWkxBY2h0YXRYSERVcURldGRBYkw1Qm1KVVVHSDI3YUFNZWVLcU4tRmlic19HM2RVemlFNFhLTVlZNl8wNWwzaW5uUEwzOF9kTWtMSUc0LUExRWtfbmp4YlBsQXNHN1dOY1E0dEdZNldxWGw1Ukxnb2ZQVUszazc5cTkxaTFBb2JuLWcwZ3lId2dVSEpvT0pqV0Q5R0xZRmJ4c212VnNZcWhTbzM5Yzg0ekdXWFJEWUx1c0lGbUlmYTNHdzBrTlNYTE5pMkk1N2lzMzY5dmMxQWNnczAzR0REYVVJUVl2UnF6VW1rdk5GZnZnV1dhM09TU3NWREk2blhHQXpRcGdkR0hOemMxelQ4ZEJ5WnUwVy1JZGZDNjRQakRWRHJQcXc1RER6czVsMlBxSG9WcXJieHUyS1c5dTJkTWt2UWo0TEpBbGFwRUQ1dmNxc2lqMS1reXZndk5jcFdVemhDTGdUQ3VWc2FsMk1JQXB1UWhWaVBZbmN2S3UyYS1VZFZfTlRFLThwak1jeHJYczU1U054SG43WU1lSjBFTW9DUQ==","email":"shadd@redhat.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWZlNWQ2ZmI5LWFhZWYtNDRiMi1hZGM0LTIwMzI5ODFmMDJiNDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtNV05qWmpWbU5EaG1aamswTVRZM09URXdNV0V5TmpreE9USmxaVFJrWXlKOS5mVm5xZlRtWWMxUFBibTBsSVpIbGdqckxyMGNGRTNKOUlROWxOU1otYWtPYlI4eEtFVkIxdl84TkE1SzRhU3ZoNzJRNV9hQlhEUmI3dzZrUldGNnhBeGR6Q0pvdmFsYmwtU2lKWTd0M29nUnBxc1o4WF82WmdGSmpfbmVTc2RFandqYm50RzVMbnhpNmRJcnJDOV8tVlVmLU1fd3hScDRNa2RMUXV5SmN2NzZPTXZsYWM1M0FzZ01aeW1lazEtY2c3X0pic1QydXZTanhQbGxoOEZpSVMzS1BMdk1PalZLWW14NTNDR19Md01rVmg3cHdfSFdFbEVDVnF1WjBlS3k2bFBuWkZhb2VJUjFyTmlkWkxBY2h0YXRYSERVcURldGRBYkw1Qm1KVVVHSDI3YUFNZWVLcU4tRmlic19HM2RVemlFNFhLTVlZNl8wNWwzaW5uUEwzOF9kTWtMSUc0LUExRWtfbmp4YlBsQXNHN1dOY1E0dEdZNldxWGw1Ukxnb2ZQVUszazc5cTkxaTFBb2JuLWcwZ3lId2dVSEpvT0pqV0Q5R0xZRmJ4c212VnNZcWhTbzM5Yzg0ekdXWFJEWUx1c0lGbUlmYTNHdzBrTlNYTE5pMkk1N2lzMzY5dmMxQWNnczAzR0REYVVJUVl2UnF6VW1rdk5GZnZnV1dhM09TU3NWREk2blhHQXpRcGdkR0hOemMxelQ4ZEJ5WnUwVy1JZGZDNjRQakRWRHJQcXc1RER6czVsMlBxSG9WcXJieHUyS1c5dTJkTWt2UWo0TEpBbGFwRUQ1dmNxc2lqMS1reXZndk5jcFdVemhDTGdUQ3VWc2FsMk1JQXB1UWhWaVBZbmN2S3UyYS1VZFZfTlRFLThwak1jeHJYczU1U054SG43WU1lSjBFTW9DUQ==","email":"shadd@redhat.com"}}}
YAML

ansible-vault encrypt --vault-password-file "$VAULT_PASS_FILE" "$TMP_CLEAN"
mv --force "$TMP_CLEAN" "$ANSIBLE_ENV_FILE"
chmod 600 "$ANSIBLE_ENV_FILE"
rm -f "$TMP_PLAIN"

echo "OK: updated $ANSIBLE_ENV_FILE (backup: $BACKUP)"
