[libvirt]
kaso.prod.spg

[installer]
installer.prod.spg ansible_host=10.168.0.1

[mrhis:children]
satellite
aap
idm

[satellite]
satellite.prod.spg ansible_host=10.168.128.1

[fullstack:children]
satellite
aap
idm
gittea
openstack

[osp:children]
openstack

[git]
gittea.prod.spg

[aap]
aap.prod.spg ansible_host=10.168.128.2

[idm]
idm.prod.spg ansible_host=10.168.128.3

[gittea]
gittea.prod.spg ansible_host=10.168.128.4

[openstack]
openstack.prod.spg ansible_host=10.168.128.5

[openshift:children]
openstack

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardX11=no'
